#!/bin/sh

current_path=`dirname $(readlink -f $0)`
nginx=`find / -name nginx -print0 | grep -FzZ 'sbin/nginx'`

if [ ! -f $nginx ]; then
	echo "=================== INSTALLATION START ====================="
	echo "Custom nginx is not installed yet! Now install..."
	apt-get update
	apt-get install -y build-essential
	apt-get install -y libpcre3-dev libssl-dev
	apt-get install -y git
	adduser --system --no-create-home --disabled-login --disabled-password --group nginx

	cd $current_path
	mkdir temp
	cd temp

	git clone https://github.com/huangqiheng/nginx-gunzip.git
	wget http://nginx.org/download/nginx-1.4.2.tar.gz
	tar xvzf nginx-1.4.2.tar.gz && cd nginx-1.4.2
	./configure \
		--prefix=/opt/nginx \
		--user=nginx \
		--group=nginx \
		--with-http_ssl_module \
		--without-http_scgi_module \
		--without-http_uwsgi_module \
		--with-http_sub_module \
		--add-module=../nginx-gunzip

	make && make install

	cd $current_path
	rm -rf ./temp

	echo "Now install php environment..."
	apt-get install -y php5-cli php5-cgi php5-fpm php5-curl php5-mcrypt
	apt-get install -y php5-memcache php5-memcached

	echo "=================== INSTALLATION FINISH ====================="
fi

prefix=`dirname $(dirname $nginx)`
access_log=$prefix/logs/access.log
error_log=$prefix/logs/error.log
fpm_log=/var/log/php5-fpm.log

chown www-data:www-data data -R

if [ "-$1" = "-" ]; then
	if ps ax | grep -v grep | grep $nginx > /dev/null
	then
		$nginx -p $prefix -c $current_path/nginx.conf -s reload
		echo "nginx.conf is reloaded"
	else
		$nginx -p $prefix -c $current_path/nginx.conf
		echo "nginx is now running"
	fi
	exit
fi 

if [ "$1" = "access" ]; then
	tail -f $access_log
	exit
fi

if [ "$1" = "error" ]; then
	tail -f $error_log
	exit
fi

if [ "$1" = "fpm" ]; then
	tail -f $fpm_log
	exit
fi

if [ "$1" = "quit" ] || [ "$1" = "close" ]  || [ "$1" = "exit" ]; then
	if [ -f $prefix/logs/nginx.pid ]; then
		$nginx -s quit
		echo "nginx quit"
	else
		echo "nginx is not running."
	fi
	exit
fi

if [ "$1" = "clean" ]; then
	truncate --size 0 $access_log
	truncate --size 0 $error_log
	truncate --size 0 $fpm_log
	exit
fi


if [ "$1" = "push" ]; then
	if [ "-$2" = "-" ]; then
		echo "Please input commit message after 'push'."
		exit
	fi

	git add --all
	git commit -m "$2"
	git push
	exit
fi

echo "Usage: "
echo "	run			: start nginx or reload nginx.conf."
echo "	run quit|close|exit	: send signal to quit nginx."
echo "	run access		: follow and view nginx access.log."
echo "	run error		: follow and view nginx error.log."
echo "	run clean		: clean nginx access.log and error.log."
echo "	run push 'msg'		: push code to github."
