#!/bin/sh

current_path=`dirname $(readlink -f $0)`
nginx=`find / -name nginx -print0 | grep -FzZ 'sbin/nginx'`

if [ "-$nginx" = "-" ]; then
	echo "Nginx is not installed yet! Please execute: sh init.sh"
	exit
fi

prefix=`dirname $(dirname $nginx)`
access_log=$prefix/logs/access.log
error_log=$prefix/logs/error.log
fpm_log=/var/log/php5-fpm.log

chown www-data:www-data data -R

if [ "-$1" = "-" ]; then
	if ps ax | grep -v grep | grep $nginx > /dev/null
	then
		$nginx -p $prefix -c $current_path/nginx.conf -s reload
		echo "nginx.conf is reloaded"
	else
		$nginx -p $prefix -c $current_path/nginx.conf
		echo "nginx is now running"
	fi
	exit
fi 

if [ "$1" = "access" ]; then
	tail -f $access_log
	exit
fi

if [ "$1" = "error" ]; then
	tail -f $error_log
	exit
fi

if [ "$1" = "fpm" ]; then
	tail -f $fpm_log
	exit
fi

if [ "$1" = "quit" ] || [ "$1" = "close" ]  || [ "$1" = "exit" ]; then
	if [ -f $prefix/logs/nginx.pid ]; then
		$nginx -s quit
		echo "nginx quit"
	else
		echo "nginx is not running."
	fi
	exit
fi

if [ "$1" = "clean" ]; then
	truncate --size 0 $access_log
	truncate --size 0 $error_log
	truncate --size 0 $fpm_log
	exit
fi


if [ "$1" = "push" ]; then
	if [ "-$2" = "-" ]; then
		echo "Please input commit message after 'push'."
		exit
	fi

	git add --all
	git commit -m "$2"
	git push
	exit
fi

echo "Usage: "
echo "	run			: start nginx or reload nginx.conf."
echo "	run install		: install nginx and others."
echo "	run quit|close|exit	: send signal to quit nginx."
echo "	run access		: follow and view nginx access.log."
echo "	run error		: follow and view nginx error.log."
echo "	run clean		: clean nginx access.log and error.log."
echo "	run push 'msg'		: push code to github."
